window.SPLASH_STRINGS = [
  "Holy hamsters!",
  "Gluten-free water!",
  "Tip your waiter!",
  "Gondor calls for aid!",
  "Made in the USA!",
  "Give me a break!",
  "Shout!",
  "Vegan-free!",
  "Totally accurate!",
  "Heavier than a kilogram of feathers!",
  "PEMDAS!",
  "Made for VSA!",
  "All I'm asking for is total perfection!",
  "Déjà vu!",
  "May contain bugs!",
  "Smash that subscribe button!",
  "Don't forget to breathe!",
  "Don't ask your doctor!",
  "Read the instructions before opening!",
  "Привет!",
  "Eat more cheeseballs!",
  "Don't forget your homework!",
  "Panic is not advised, but it is recommended!",
  "Nobody asked for your opinion!",
  "Try the calamari!",
  "Oh, it's you again!",
  "I'm ready!",
  "Pay as little taxes as legally permissible!",
  "Don't be naïve!",
  "What the fridge!",
  "May cause intense anxiety!",
  "Pineapple on pizza is good!",
  "Wow, nice shoes!",
  "Watch out for the mafia!",
  "That's kinda dicey!",
  "Это всего лишь несколько слов!",
  "Indie!",
  "Don't forget to lock up the chinchillas!",
  "Another one bites the dust!",
  "Check under your bed for Chuck Norris!",
  "Carry on!",
  "Don't let a drunk chicken stomp on your crops!",
  "Houston, we have a major problem!",
  "It gets worse, trust me!",
  "So many pixels!",
  "Oh come on, Patrick!",
  "Don't be scared of swamp puppies!",
  "Let's shoot for 40!",
  "Todd is just a garbage last name!",
  "Licking ice cream is just wrong!",
  "Touch grass!",
  "Timmy can play golf with a bowling ball!",
  "Wheels are more abundant than doors!",
  "Three little birds!",
  "Ha roligt!",
  "Nyango Star destroys the drums!",
  "You underestimate my power!",
  "That's some good beans!",
  "Spoons are not inherently evil!",
  "Made with Javascript!",
  "Your shoe is untied!",
  "Good afternoon, good evening, and good night!",
  "It's elementary, my dear Watson!",
  "Probably doesn't contain peanuts, but who knows!",
  "Produced in a two-story house!",
  "I'm going on an adventure!",
  "Dream on!",
  "Chuck Norris can kill two stones with one bird!",
  "Grenade!",
  "Seal pups are pretty average!",
  "Take a break from your phone already!",
  "Flying straight isn't a good idea!",
  "Still a work in progress!",
  "Technoblade never dies!",
  "Do not go gentle into that good night!",
  "Everything is awesome!",
  "Look behind you!",
  "It's Schoology, not Schoalagy!",
  "It is Thursday, my dudes!",
  "That's a lotta damage!",
  "Ask the Panzer of the Lake!",
  "Feedback is greatly appreciated!",
  "Emotional damage!",
  "Brother, may I have some oats!",
  "Think for yourself!",
  "Tell your friends!",
  "The Dyatlov Pass wasn't just an avalanche!",
  "Agency FB is pretty cool!",
  "Support the troops!",
  "You may not sleep now, there are monsters nearby!",
  "Microsoft One Drive is malware!",
  "Attack the D point!",
  "Do a barrel roll!",
  "Try listening to real music!",
  "It is Wednesday, my dudes!",
  "Don't put rubber bands in your hair!",
  "Poyo!",
  "Free to play!",
  "Around 4.5k lines of code!",
  "I'm tired of this, Grandpa!"
];
